# Generated by Django 3.1.2 on 2021-07-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
